export const german: Readonly<Record<string, string>> = {
  "Workforce & shifts": "Personal & Schichten",
  "My day": "Mein Tag",
  "Weekly plan": "Wochenplan",
  "Schedule import": "Dienstplan importieren",
  Configuration: "Konfiguration",
  "Your assignment": "Dein Einsatz",
  "Other zones": "Weitere Bereiche",
  "Shift leaders": "Schichtleitung",
  "Floating support": "Springer",
  Maintenance: "Wartung",
  Compensation: "Kompensation",
  Training: "Weiterbildung",
  Vacation: "Ferien",
  Accident: "Unfall",
  "Sick leave": "Krankheit",
  Off: "Frei",
  Work: "Arbeit",
  "No schedule yet": "Noch kein Dienstplan",
  "No assignment yet": "Noch kein Einsatz zugeteilt",
  "Coverage gaps": "Unbesetzte Bereiche",
  Date: "Datum",
  Shift: "Schicht",
  Person: "Person",
  Zone: "Bereich",
  Duty: "Aufgabe",
  Phone: "Handy",
  "Start time": "Beginn",
  "End time": "Ende",
  Assign: "Zuteilen",
  Save: "Speichern",
  Cancel: "Abbrechen",
  Refresh: "Aktualisieren",
  Delete: "Löschen",
  History: "Verlauf",
  "No phone": "Kein Handy",
  "No zone": "Kein Bereich",
  "Zone coverage": "Bereichsbesetzung",
  "Team Leader": "Teamleiter",
  Technician: "Techniker",
  Administrator: "Administrator",
  "Preview import": "Import prüfen",
  "Import plan": "Plan importieren",
  "Choose a person for the email": "Person für die E-Mail auswählen",
  "CSV or email file": "CSV- oder E-Mail-Datei",
  "Paste CSV or email content": "CSV oder E-Mail-Inhalt einfügen",
  Format: "Format",
  Email: "E-Mail",
  "Personal schedules": "Persönliche Dienstpläne",
  "No records for this date.": "Keine Einträge für dieses Datum.",
  "Select a person": "Person auswählen",
  "Import completed.": "Import abgeschlossen.",
  "Saved.": "Gespeichert.",
  "Deleted. History is retained.": "Gelöscht. Der Verlauf bleibt erhalten.",
  "Preparing…": "Wird vorbereitet…",
  "Loading…": "Wird geladen…",
  "Saving…": "Wird gespeichert…",
  "Preview required before import.":
    "Vor dem Import ist eine Prüfung erforderlich.",
  "Times use the site time zone.":
    "Die Zeiten entsprechen der Zeitzone des Standorts.",
  "Assignment details": "Einsatzdetails",
  Monday: "Montag",
  Tuesday: "Dienstag",
  Wednesday: "Mittwoch",
  Thursday: "Donnerstag",
  Friday: "Freitag",
  Saturday: "Samstag",
  Sunday: "Sonntag",
  Name: "Name",
  ID: "ID",
  Team: "Team",
  "Home zone": "Stammbereich",
  "Worker profiles": "Personalprofile",
  "Shift definitions": "Schichtarten",
  "Targets and phones": "Bereiche und Handys",
  Teams: "Teams",
  Add: "Hinzufügen",
  Remove: "Entfernen",
  "Active days (0 Sunday – 6 Saturday)": "Aktive Tage (0 Sonntag – 6 Samstag)",
  "Keep phone labels unique across zones.":
    "Handybezeichnungen müssen bereichsübergreifend eindeutig sein.",
  "Existing assignments retain their original labels and times.":
    "Bestehende Einsätze behalten ihre ursprünglichen Angaben und Zeiten.",
  "Manual schedule": "Manueller Dienstplan",
  Status: "Status",
  Source: "Quelle",
  Result: "Ergebnis",
  Create: "Anlegen",
  Replace: "Ersetzen",
  Unchanged: "Unverändert",
  "The plan changed or has dependent assignments. Reload before saving.":
    "Der Plan wurde geändert oder enthält abhängige Einsätze. Vor dem Speichern neu laden.",
  "Enter or import a compatible working schedule for this person first.":
    "Zuerst einen passenden Dienstplan für diese Person erfassen oder importieren.",
  "This person or phone is already assigned during this interval.":
    "Diese Person oder dieses Handy ist in diesem Zeitraum bereits zugeteilt.",
  "Check the plan fields and dates.": "Bitte die Planfelder und Daten prüfen.",
  "The file contains unsupported or invalid rows. Use the CSV template or the supported schedule email.":
    "Die Datei enthält ungültige oder nicht unterstützte Zeilen. Bitte die CSV-Vorlage oder die unterstützte Dienstplan-E-Mail verwenden.",
  "You do not have permission to change this plan.":
    "Du hast keine Berechtigung, diesen Plan zu ändern.",
  "This local time is missing or repeated due to a clock change. Use an unambiguous interval.":
    "Diese Ortszeit ist wegen einer Zeitumstellung nicht eindeutig. Bitte einen eindeutigen Zeitraum verwenden.",
  "Workforce is unavailable. Sign in again or retry.":
    "Die Personalplanung ist nicht verfügbar. Bitte erneut anmelden oder versuchen.",
  Language: "Sprache",
  English: "Englisch",
  German: "Deutsch",
  Access: "Zugriff",
  "Account created:": "Konto erstellt:",
  "Accounts for this site": "Konten dieses Standorts",
  Actions: "Aktionen",
  Active: "Aktiv",
  "Add KPI": "Kennzahl hinzufügen",
  "Add a daily CSV": "Tages-CSV hinzufügen",
  "Add area rule": "Bereichsregel hinzufügen",
  "Add daily files and review their saved history and source rows.":
    "Tagesdateien hinzufügen und gespeicherten Verlauf sowie Quelldaten prüfen.",
  "Add follow-up": "Ergänzung hinzufügen",
  "Add value correction": "Wertkorrektur hinzufügen",
  "Adjust the dates or dimension filters.": "Datum oder Filter anpassen.",
  Administration: "Administration",
  "Administration overview": "Administrationsübersicht",
  "Administration sections": "Administrationsbereiche",
  "Administration · Data Analysis": "Administration · Datenanalyse",
  "Administrator:": "Administrator:",
  "Admitted rows": "Übernommene Zeilen",
  "Alarm minutes/day": "Alarmminuten/Tag",
  "Alarm totals do not indicate whether equipment is blocked or repaired. Missing dates do not mean zero activity.":
    "Alarmsummen zeigen nicht, ob Anlagen gesperrt oder repariert sind. Fehlende Tage bedeuten keine Nullaktivität.",
  "All areas": "Alle Bereiche",
  "All categories": "Alle Kategorien",
  "All departments": "Alle Abteilungen",
  "All eligible matching historical rows contribute to totals. Rankings show up to 100 of":
    "Alle passenden historischen Zeilen gehen in die Summen ein. Ranglisten zeigen bis zu 100 von",
  "All entries": "Alle Einträge",
  "All sectors": "Alle Hallen",
  "All users · All departments": "Alle Benutzer · Alle Abteilungen",
  "An administrator can import daily files for analysis.":
    "Ein Administrator kann Tagesdateien für die Analyse importieren.",
  "Analysis templates": "Analysevorlagen",
  "Analytical snapshot": "Analyseübersicht",
  "Analytical summary": "Analysezusammenfassung",
  "Apply filters": "Filter anwenden",
  "Area / Bereich": "Bereich",
  "Area filter": "Bereichsfilter",
  "Area → sector rules (": "Bereich → Halle: Regeln (",
  "Areas rank by the selected month's total frequency. Up to 100 areas; scroll the ranking and matrix for more. Frequency and duration are overlaid on separately labelled axes. Alarm duration is not plant downtime.":
    "Bereiche sind nach Gesamthäufigkeit im gewählten Monat sortiert. Bis zu 100 Bereiche; für weitere Einträge scrollen. Häufigkeit und Dauer verwenden getrennte Achsen. Alarmdauer ist keine Anlagenstillstandszeit.",
  "Assign responsibility": "Verantwortung zuweisen",
  "At reference": "Auf Referenzniveau",
  "Available profiles": "Verfügbare Profile",
  "Awaiting final outcome": "Endergebnis ausstehend",
  "Above reference": "Über Referenz",
  "Below reference": "Unter Referenz",
  "Bereich frequency by day · highest first":
    "Bereichshäufigkeit pro Tag · absteigend",
  "Betriebsmittelkennzeichen identifies a component, such as a sensor or motor.":
    "Das Betriebsmittelkennzeichen identifiziert eine Komponente, etwa einen Sensor oder Motor.",
  Blocked: "Gesperrt",
  "Blocked & restored equipment": "Gesperrte und wiederhergestellte Anlagen",
  Breadcrumb: "Navigationspfad",
  "CSV file": "CSV-Datei",
  Category: "Kategorie",
  "Category filter": "Kategoriefilter",
  "Change password": "Passwort ändern",
  "Choices follow the filters above. Changing a filter clears the following filters.":
    "Die Auswahl folgt den obigen Filtern. Änderungen setzen nachfolgende Filter zurück.",
  "Choose a nonempty CSV of at most 5 MiB.":
    "Eine nicht leere CSV mit höchstens 5 MiB auswählen.",
  "Choose another month or import a daily CSV.":
    "Einen anderen Monat wählen oder eine Tages-CSV importieren.",
  "Choose up to eight KPIs. Choose an exact prepared Meldetext for each KPI. Goals use the same daily-average unit as the KPI; leave a goal empty to compare with all imported history. Lower is better.":
    "Bis zu acht Kennzahlen auswählen, jeweils mit genauem aufbereitetem Meldetext. Ziele verwenden dieselbe Einheit des Tagesdurchschnitts. Ein leeres Ziel vergleicht mit dem gesamten importierten Verlauf. Niedrigere Werte sind besser.",
  "Choose your own password": "Eigenes Passwort wählen",
  "Clear fields": "Felder leeren",
  "Clear filters": "Filter zurücksetzen",
  "Clear search": "Suche löschen",
  "Click a column title to cycle ascending, descending and off. Numbers show sorting priority across the whole file.":
    "Ein Spaltenklick wechselt zwischen aufsteigend, absteigend und unsortiert. Zahlen zeigen die Sortierpriorität für die gesamte Datei.",
  "Close issue": "Problem abschliessen",
  "Collapse repeated spaces": "Mehrfache Leerzeichen zusammenfassen",
  "Column filters": "Spaltenfilter",
  "Comparison between months": "Monatsvergleich",
  "Component reference · Unverified. This report records an observation.":
    "Komponentenreferenz · Ungeprüft. Dieser Bericht dokumentiert eine Beobachtung.",
  "Confirm new password": "Neues Passwort bestätigen",
  "Confirm reporting date:": "Berichtsdatum bestätigen:",
  "Connect the local API to open the analytical workspace.":
    "Lokale API verbinden, um die Analyse zu öffnen.",
  "Connecting…": "Verbindung wird hergestellt…",
  "Contributing source rows": "Zugehörige Quellzeilen",
  "Correct entry": "Eintrag korrigieren",
  "Could not load components.": "Komponenten konnten nicht geladen werden.",
  "Could not load entries.": "Einträge konnten nicht geladen werden.",
  "Could not validate these filters. Check the values and try again.":
    "Filter konnten nicht geprüft werden. Werte prüfen und erneut versuchen.",
  "Create a user": "Benutzer anlegen",
  "Create accounts, assign profiles and manage platform access.":
    "Konten anlegen, Profile zuweisen und Plattformzugriff verwalten.",
  "Create individual accounts and assign access to this local site.":
    "Individuelle Konten anlegen und Zugriff auf diesen Standort zuweisen.",
  "Create user": "Benutzer anlegen",
  "Cumulative share uses all matching groups across the selected months. Solid bars include the group reaching 80%.":
    "Der kumulierte Anteil umfasst alle passenden Gruppen der gewählten Monate. Volle Balken schliessen die Gruppe ein, die 80 % erreicht.",
  "Current initial password": "Aktuelles Erstpasswort",
  Daily: "Täglich",
  "Daily category canvas": "Tagesübersicht nach Kategorien",
  "Daily files. One persistent reporting history.":
    "Tagesdateien. Ein dauerhafter Berichtsverlauf.",
  "Daily overview": "Tagesübersicht",
  Damaged: "Beschädigt",
  "Data Analysis · v1": "Datenanalyse · v1",
  "Data administration": "Datenverwaltung",
  "Data analysis": "Datenanalyse",
  "Data preparation": "Datenaufbereitung",
  "Data preparation & sector classification":
    "Datenaufbereitung und Hallenzuordnung",
  "Dauer · minutes": "Dauer · Minuten",
  "Delete entry": "Eintrag löschen",
  "Delete profile": "Profil löschen",
  "Demo user": "Demobenutzer",
  "Department / Halle": "Abteilung / Halle",
  "Department filter": "Abteilungsfilter",
  "Department handover matrix": "Übergabematrix der Abteilungen",
  "Department matrix": "Abteilungsmatrix",
  Description: "Beschreibung",
  Details: "Details",
  "Details, work reference and problem analysis":
    "Details, Arbeitsreferenz und Problemanalyse",
  Disable: "Deaktivieren",
  Disabled: "Deaktiviert",
  "Discuss in meeting": "Im Meeting besprechen",
  "Dismiss initial password": "Erstpasswort ausblenden",
  "Download preserved original": "Gespeichertes Original herunterladen",
  Due: "Fällig",
  "Due date": "Fälligkeitsdatum",
  "Duplicate reporting date": "Doppeltes Berichtsdatum",
  "Duration versus frequency · up to 100 groups":
    "Dauer und Häufigkeit · bis zu 100 Gruppen",
  "Duration · minutes": "Dauer · Minuten",
  "Earlier revisions": "Frühere Versionen",
  "Earlier versions and follow-up remain available.":
    "Frühere Versionen und Ergänzungen bleiben verfügbar.",
  Enable: "Aktivieren",
  "Entries you published": "Deine veröffentlichten Einträge",
  "Entry date": "Eintragsdatum",
  "Equipment reference history": "Verlauf der Anlagenreferenz",
  "Equipment restrictions, completed repairs and their sector will appear here.":
    "Anlageneinschränkungen, abgeschlossene Reparaturen und ihre Halle erscheinen hier.",
  "Equipment status · Not connected": "Anlagenstatus · Nicht verbunden",
  "Exact minutes, rounded to 2 decimals (for example, 1.25).":
    "Genaue Minuten, auf zwei Dezimalstellen gerundet (z. B. 1.25).",
  "Exact seconds for this filter. Type an exact value; up to 200 suggestions.":
    "Genaue Sekunden für diesen Filter. Exakten Wert eingeben; bis zu 200 Vorschläge.",
  "Excluded from analysis:": "Von der Analyse ausgeschlossen:",
  "Explicit value corrections (": "Explizite Wertkorrekturen (",
  "Explore data · rankings and trends":
    "Daten erkunden · Ranglisten und Trends",
  "External work reference": "Externe Arbeitsreferenz",
  Feedback: "Rückmeldung",
  "Feedback due": "Rückmeldung fällig",
  Field: "Feld",
  File: "Datei",
  "File / reporting date": "Datei / Berichtsdatum",
  "File import volume": "Importvolumen",
  "File size · bytes": "Dateigrösse · Bytes",
  "Files & source rows": "Dateien & Quellzeilen",
  "Files and accepted rows persist in the database. An existing reporting date cannot be replaced.":
    "Dateien und übernommene Zeilen bleiben in der Datenbank. Ein vorhandenes Berichtsdatum kann nicht ersetzt werden.",
  "Filter Betriebsmittelkennzeichen": "Betriebsmittelkennzeichen filtern",
  "Filtered history": "Gefilterter Verlauf",
  "Filtering one unverified equipment reference. Reset filters to see all entries.":
    "Eine ungeprüfte Anlagenreferenz ist gefiltert. Filter zurücksetzen, um alle Einträge zu sehen.",
  "Find component": "Komponente finden",
  "Follow-up and coordination": "Ergänzung und Koordination",
  Frequency: "Häufigkeit",
  "Frequency and alarm minutes per day": "Häufigkeit und Alarmminuten pro Tag",
  "Frequency and duration over time": "Häufigkeit und Dauer im Zeitverlauf",
  From: "Von",
  "From your technicians": "Von deinen Technikern",
  "Give this password to the user securely. It is shown once and must be changed at first sign-in.":
    "Dieses Passwort sicher an den Benutzer übermitteln. Es wird einmal angezeigt und muss bei der ersten Anmeldung geändert werden.",
  Goal: "Ziel",
  Group: "Gruppe",
  "Group behavior by reporting period":
    "Gruppenverhalten nach Berichtszeitraum",
  "Group by": "Gruppieren nach",
  "Group totals ·": "Gruppensummen ·",
  "Handover entry": "Übergabeeintrag",
  "Handover views": "Übergabeansichten",
  "Highlight on Start": "Auf Start hervorheben",
  Highlighted: "Hervorgehoben",
  "Historical daily average": "Historischer Tagesdurchschnitt",
  "Historical trend": "Historischer Trend",
  "Hitliste-YYYYMMDD.csv · UTF-16 LE with BOM · semicolon separated · maximum 5 MiB.":
    "Hitliste-YYYYMMDD.csv · UTF-16 LE mit BOM · Semikolon-getrennt · höchstens 5 MiB.",
  "Häufigkeit → integer; Dauer → exact seconds, displayed as minutes; Bereich, Betriebsmittelkennzeichen, Meldetext, Typ and Meldegruppe → text. Commas, umlauts and code punctuation are preserved.":
    "Häufigkeit → Ganzzahl; Dauer → genaue Sekunden, Anzeige in Minuten; Bereich, Betriebsmittelkennzeichen, Meldetext, Typ und Meldegruppe → Text. Kommas, Umlaute und Satzzeichen bleiben erhalten.",
  "IOP · Go to Start": "IOP · Zur Startseite",
  "Import & prepare": "Importieren & aufbereiten",
  "Import CSV": "CSV importieren",
  "Import a daily CSV first.": "Zuerst eine Tages-CSV importieren.",
  "Import complete": "Import abgeschlossen",
  "Import diagnostics": "Importdiagnose",
  "Import failed": "Import fehlgeschlagen",
  "Import files": "Dateien importieren",
  "Import history": "Importverlauf",
  "Import inspection details": "Prüfdetails des Imports",
  "Import rejected": "Import abgelehnt",
  "Import review": "Importprüfung",
  "Important published reports, repair notes and handovers will appear here.":
    "Wichtige Berichte, Reparaturnotizen und Übergaben erscheinen hier.",
  "Imported dates this month": "Importierte Tage dieses Monats",
  "Imported file": "Importierte Datei",
  "Imports & source data": "Importe & Quelldaten",
  "In progress": "In Bearbeitung",
  "Industrial Operations Platform": "Plattform für industrielle Abläufe",
  Information: "Information",
  "Initial credentials": "Erstzugangsdaten",
  "Initial password:": "Erstpasswort:",
  "Inspection counts describe checked source rows; admitted rows confirm what was saved. Repeated rows within a file are separate from a duplicate reporting date.":
    "Prüfzahlen beschreiben geprüfte Quellzeilen; übernommene Zeilen bestätigen die Speicherung. Wiederholte Zeilen innerhalb einer Datei unterscheiden sich von einem doppelten Berichtsdatum.",
  "Inspection needed": "Prüfung erforderlich",
  "Inspection:": "Prüfung:",
  "Invalid inspected rows": "Ungültige geprüfte Zeilen",
  Issue: "Problem",
  "Issue filter": "Problemfilter",
  "Issue state": "Problemstatus",
  Journal: "Journal",
  "KPI settings & goals": "Kennzahlen und Ziele",
  "KPI settings could not be loaded. Retry loading settings.":
    "Kennzahleneinstellungen konnten nicht geladen werden. Erneut versuchen.",
  "KPI settings saved.": "Kennzahleneinstellungen gespeichert.",
  "Keep current state": "Aktuellen Status beibehalten",
  Label: "Bezeichnung",
  "Latest imported month": "Zuletzt importierter Monat",
  "Latest update": "Letzte Aktualisierung",
  Line: "Zeile",
  "Loading analytical overview…": "Analyseübersicht wird geladen…",
  "Loading components…": "Komponenten werden geladen…",
  "Loading entry…": "Eintrag wird geladen…",
  "Loading handover…": "Übergabe wird geladen…",
  "Loading historical analysis…": "Historische Analyse wird geladen…",
  "Loading operational updates…": "Betriebliche Meldungen werden geladen…",
  "Loading source rows…": "Quellzeilen werden geladen…",
  "Local account": "Lokales Konto",
  "Local demonstration account": "Lokales Demokonto",
  "Maintain historical preparation rules and KPI goals.":
    "Aufbereitungsregeln und Kennzahlziele verwalten.",
  "Manage daily files, import quality and reporting settings.":
    "Tagesdateien, Importqualität und Berichtseinstellungen verwalten.",
  "Manage platform access, source data and reporting settings.":
    "Plattformzugriff, Quelldaten und Berichtseinstellungen verwalten.",
  "Manage users": "Benutzer verwalten",
  Measure: "Massnahme",
  "Meeting date": "Meetingdatum",
  "Meeting preparation": "Meetingvorbereitung",
  Minutes: "Minuten",
  "Month total:": "Monatssumme:",
  "Month ·": "Monat ·",
  Monthly: "Monatlich",
  "Monthly KPI comparison": "Monatlicher Kennzahlenvergleich",
  "Months ·": "Monate ·",
  More: "Mehr",
  "More components": "Weitere Komponenten",
  "More entries": "Weitere Einträge",
  "More open issues": "Weitere offene Probleme",
  "My entries": "Meine Einträge",
  "Needs attention": "Handlungsbedarf",
  "New KPI": "Neue Kennzahl",
  "New entry": "Neuer Eintrag",
  "New handover entry": "Neuer Übergabeeintrag",
  "New password": "Neues Passwort",
  "Next rows": "Nächste Zeilen",
  "No active highlights.": "Keine aktiven Hervorhebungen.",
  "No additional details.": "Keine weiteren Details.",
  "No analytical history is available yet. An authorized operator can import a daily CSV in Data Analysis.":
    "Noch kein Analyseverlauf verfügbar. Ein berechtigter Benutzer kann in der Datenanalyse eine Tages-CSV importieren.",
  "No departments are configured yet. You can publish site-wide information.":
    "Noch keine Abteilungen konfiguriert. Standortweite Informationen können erfasst werden.",
  "No eligible imported dates in this month":
    "Keine berücksichtigten importierten Tage in diesem Monat",
  "No entries for this day.": "Keine Einträge für diesen Tag.",
  "No import attempts are available yet.":
    "Noch keine Importversuche vorhanden.",
  "No imported codes match. You can still report on this area.":
    "Keine passenden importierten Kennzeichen. Ein Bericht für diesen Bereich ist dennoch möglich.",
  "No imported coverage": "Keine importierten Daten",
  "No imported files to browse": "Keine importierten Dateien vorhanden",
  "No issues need attention for this selection.":
    "Kein Handlungsbedarf für diese Auswahl.",
  "No matching combination. Choose a suggested value or clear the filters.":
    "Keine passende Kombination. Einen vorgeschlagenen Wert wählen oder Filter zurücksetzen.",
  "No matching records": "Keine passenden Datensätze",
  "No open issues have been reported for this selection.":
    "Keine offenen Probleme für diese Auswahl gemeldet.",
  "No rows match these filters. Clear or adjust the column filters.":
    "Keine passenden Zeilen. Spaltenfilter zurücksetzen oder anpassen.",
  "No specific area": "Kein bestimmter Bereich",
  "No specific component": "Keine bestimmte Komponente",
  "No unresolved issues.": "Keine ungelösten Probleme.",
  "No updates for this selection": "Keine Meldungen für diese Auswahl",
  "No updates yet. Share what the next team should know.":
    "Noch keine Meldungen. Teile mit, was das nächste Team wissen sollte.",
  "No workforce information is available yet.":
    "Noch keine Personalinformationen verfügbar.",
  "Normalize Unicode (NFC)": "Unicode normalisieren (NFC)",
  "Not reported": "Nicht gemeldet",
  "Occurrences/day": "Vorkommnisse/Tag",
  "Only the first diagnostics are shown. Download the original file to investigate the remaining rows.":
    "Nur die ersten Diagnosen werden angezeigt. Zur Prüfung weiterer Zeilen die Originaldatei herunterladen.",
  Open: "Offen",
  "Open Data Analysis": "Datenanalyse öffnen",
  "Open Import & prepare to add a daily file.":
    "Importieren & aufbereiten öffnen, um eine Tagesdatei hinzuzufügen.",
  "Open Shift Handover": "Schichtübergabe öffnen",
  "Open and in progress": "Offen und in Bearbeitung",
  "Open reports": "Berichte öffnen",
  "Open work and important updates for the next team.":
    "Offene Arbeiten und wichtige Meldungen für das nächste Team.",
  "Operational handover updates": "Betriebliche Übergabemeldungen",
  "Operational updates": "Betriebliche Meldungen",
  "Operational updates · Not connected":
    "Betriebliche Meldungen · Nicht verbunden",
  Operations: "Betrieb",
  "Operations · Data Analysis": "Betrieb · Datenanalyse",
  Outcome: "Ergebnis",
  "Overview date": "Übersichtsdatum",
  Password: "Passwort",
  Period: "Zeitraum",
  "Platform administration": "Plattformadministration",
  "Please wait…": "Bitte warten…",
  "Preparation could not be saved.":
    "Aufbereitung konnte nicht gespeichert werden.",
  "Preparation saved. Return to analysis to see the updated history.":
    "Aufbereitung gespeichert. Zur Analyse wechseln, um den aktualisierten Verlauf zu sehen.",
  "Prepared values reflect the current reporting rules. The preserved original remains unchanged.":
    "Aufbereitete Werte entsprechen den aktuellen Berichtsregeln. Das gespeicherte Original bleibt erhalten.",
  "Previous rows": "Vorherige Zeilen",
  "Processing CSV…": "CSV wird verarbeitet…",
  Profile: "Profil",
  "Profile preview": "Profilvorschau",
  "Profile view": "Profilansicht",
  "Publication failed.": "Veröffentlichung fehlgeschlagen.",
  "Publish update": "Meldung veröffentlichen",
  "Reason for correction": "Korrekturgrund",
  "Reason:": "Grund:",
  Received: "Empfangen",
  Recorded: "Erfasst",
  "Recorded activity by sector.": "Erfasste Aktivität nach Halle.",
  "Recover import outcome": "Importergebnis ermitteln",
  "Refresh history": "Verlauf aktualisieren",
  "Refresh import history and review any received attempt before retrying.":
    "Importverlauf aktualisieren und empfangene Versuche vor einem erneuten Import prüfen.",
  "Refresh overview": "Übersicht aktualisieren",
  "Refresh updates": "Meldungen aktualisieren",
  "Rejected rows": "Abgelehnte Zeilen",
  "Reload file": "Datei neu laden",
  "Reload saved settings": "Gespeicherte Einstellungen laden",
  "Remove KPI": "Kennzahl entfernen",
  "Remove correction": "Korrektur entfernen",
  "Remove rule": "Regel entfernen",
  "Reopen issue": "Problem wieder öffnen",
  Repaired: "Repariert",
  "Repeated rows within file": "Wiederholte Zeilen in der Datei",
  "Replace one exact source value for analysis. No automatic spelling guesses.":
    "Einen genauen Quellwert für die Analyse ersetzen. Keine automatische Rechtschreibkorrektur.",
  "Replace the initial password before opening your workspace. Sign in again after the change.":
    "Erstpasswort vor dem Öffnen des Arbeitsbereichs ersetzen. Danach erneut anmelden.",
  Reported: "Gemeldet",
  "Reported alarm frequency": "Gemeldete Alarmhäufigkeit",
  "Reported blocked": "Als gesperrt gemeldet",
  "Reported by": "Gemeldet von",
  "Reported condition": "Gemeldeter Zustand",
  "Reporting dates come from file names; reporting windows are unknown. Missing dates are not zero activity. Monthly comparisons use only imported dates.":
    "Berichtsdaten stammen aus Dateinamen; Zeitfenster sind unbekannt. Fehlende Tage sind keine Nullaktivität. Monatsvergleiche verwenden nur importierte Tage.",
  "Reporting settings": "Berichtseinstellungen",
  "Resolution outcome": "Abschlussergebnis",
  Resolved: "Gelöst",
  "Resolved · Close issue": "Gelöst · Problem abschliessen",
  Responsible: "Verantwortlich",
  "Responsible person": "Verantwortliche Person",
  "Responsible ·": "Verantwortlich ·",
  Restored: "Wiederhergestellt",
  "Retry choices": "Auswahl erneut laden",
  "Retry connection": "Verbindung erneut versuchen",
  "Return to administration": "Zur Administration",
  Review: "Prüfen",
  "Review accepted files and unsuccessful attempts. Counts shown here are saved rows; Review includes inspection details.":
    "Übernommene Dateien und erfolglose Versuche prüfen. Zahlen zeigen gespeicherte Zeilen; die Prüfung enthält weitere Details.",
  "Review existing import": "Vorhandenen Import prüfen",
  Rows: "Zeilen",
  "Save KPI settings": "Kennzahleneinstellungen speichern",
  "Save correction": "Korrektur speichern",
  "Save historical preparation": "Historische Aufbereitung speichern",
  "Save update": "Aktualisierung speichern",
  "Saving KPI settings…": "Kennzahleneinstellungen werden gespeichert…",
  "Saving applies these rules to the complete historical analysis. Original files and imported values remain preserved.":
    "Speichern wendet die Regeln auf die gesamte historische Analyse an. Originaldateien und importierte Werte bleiben erhalten.",
  "Scrollable department matrix": "Scrollbare Abteilungsmatrix",
  Search: "Suchen",
  "Search entries": "Einträge suchen",
  "Search handover history": "Übergabeverlauf durchsuchen",
  "Search history": "Verlauf durchsuchen",
  Sector: "Halle",
  "Sector / Halle": "Halle",
  "Select a department to catch up with your team":
    "Eine Abteilung wählen, um die Meldungen deines Teams zu sehen",
  "Select a user": "Benutzer auswählen",
  "Select a user in the header to open the workspace.":
    "Oben einen Benutzer wählen, um den Arbeitsbereich zu öffnen.",
  "Select a user in the header to see the available information.":
    "Oben einen Benutzer wählen, um verfügbare Informationen zu sehen.",
  "Select an area to choose a component.":
    "Einen Bereich wählen, um eine Komponente auszuwählen.",
  "Select an error": "Fehler auswählen",
  "Select at least one month.": "Mindestens einen Monat auswählen.",
  "Select one or more months, then apply. Selected months stay active in all detail views. Clear filters restores all available months.":
    "Einen oder mehrere Monate auswählen und anwenden. Die Auswahl bleibt in allen Detailansichten aktiv. Filter zurücksetzen stellt alle Monate wieder her.",
  "Select your local user": "Lokalen Benutzer auswählen",
  "Selected department": "Gewählte Abteilung",
  "Selected file:": "Gewählte Datei:",
  "Settings could not be saved. Check the values, or reload saved settings if another edit changed them.":
    "Einstellungen konnten nicht gespeichert werden. Werte prüfen oder bei zwischenzeitlichen Änderungen erneut laden.",
  "Share an update or search earlier history.":
    "Eine Meldung teilen oder den bisherigen Verlauf durchsuchen.",
  "Shift Handover": "Schichtübergabe",
  "Shifts & departments": "Schichten & Abteilungen",
  "Showing the most recent 1,000 import attempts.":
    "Die letzten 1.000 Importversuche werden angezeigt.",
  "Sign in": "Anmelden",
  "Sign in to IOP": "Bei IOP anmelden",
  "Sign out": "Abmelden",
  "Sign-in failed.": "Anmeldung fehlgeschlagen.",
  "Site-wide": "Standortweit",
  "Site-wide analytical snapshot": "Standortweite Analyseübersicht",
  "Site-wide highlights": "Standortweite Hervorhebungen",
  "Site-wide information": "Standortweite Informationen",
  "Skip to workspace": "Zum Arbeitsbereich springen",
  "Source rows": "Quellzeilen",
  "Source rows could not be loaded. Reload the file to use its current preparation.":
    "Quellzeilen konnten nicht geladen werden. Datei neu laden, um die aktuelle Aufbereitung zu verwenden.",
  Start: "Start",
  "Start department": "Startabteilung",
  "Start highlights only": "Nur Start-Hervorhebungen",
  "Start page": "Startseite",
  "Status is unknown until operational records are available.":
    "Der Status ist unbekannt, bis betriebliche Einträge verfügbar sind.",
  Summary: "Zusammenfassung",
  "Summary, equipment code or work reference":
    "Zusammenfassung, Anlagenkennzeichen oder Arbeitsreferenz",
  "Team and role profile: not configured.":
    "Team- und Rollenprofil: nicht konfiguriert.",
  "Technician · Task Force · Team Leader:":
    "Techniker · Task Force · Teamleiter:",
  "The change failed.": "Änderung fehlgeschlagen.",
  "The final outcome is not yet known. Use Review or Recover import outcome in the history before attempting another upload.":
    "Das Endergebnis ist noch unbekannt. Vor einem erneuten Upload im Verlauf prüfen oder das Importergebnis ermitteln.",
  "The import operation could not be completed.":
    "Der Import konnte nicht abgeschlossen werden.",
  "The operation could not be completed.":
    "Der Vorgang konnte nicht abgeschlossen werden.",
  "The operation failed.": "Der Vorgang ist fehlgeschlagen.",
  "The overview could not be loaded. Try refreshing.":
    "Die Übersicht konnte nicht geladen werden. Bitte aktualisieren.",
  "The server validates the CSV and reports row counts and diagnostics after processing.":
    "Der Server prüft die CSV und meldet Zeilenzahlen sowie Diagnosen nach der Verarbeitung.",
  "The update failed.": "Aktualisierung fehlgeschlagen.",
  "There is no publication source yet. This is a placeholder.":
    "Noch keine Veröffentlichungsquelle vorhanden. Dies ist ein Platzhalter.",
  "This date already has an accepted file. The existing data was preserved; this upload added no rows.":
    "Für dieses Datum existiert bereits eine übernommene Datei. Vorhandene Daten bleiben erhalten; dieser Upload hat keine Zeilen hinzugefügt.",
  "This reporting date already has an accepted file:":
    "Für dieses Berichtsdatum existiert bereits eine übernommene Datei:",
  "This update is added to the history. The original report is retained.":
    "Diese Ergänzung wird dem Verlauf hinzugefügt. Der ursprüngliche Bericht bleibt erhalten.",
  Through: "Bis",
  "Top 10 by duration · Pareto": "Top 10 nach Dauer · Pareto",
  "Top 10 by frequency · Pareto": "Top 10 nach Häufigkeit · Pareto",
  "Top Bereiche by frequency": "Top-Bereiche nach Häufigkeit",
  "Track as an open issue": "Als offenes Problem verfolgen",
  "Track as issue": "Als Problem verfolgen",
  "Trim outer spaces": "Äussere Leerzeichen entfernen",
  "Types:": "Typen:",
  Unassigned: "Nicht zugewiesen",
  "Unclassified rows at import": "Beim Import nicht zugeordnete Zeilen",
  Unknown: "Unbekannt",
  "Unverified reference": "Ungeprüfte Referenz",
  "Update / reason": "Ergänzung / Grund",
  "Update type": "Art der Aktualisierung",
  "Updating compatible choices…": "Passende Auswahl wird aktualisiert…",
  "Updating users…": "Benutzer werden aktualisiert…",
  "Use a filename with a valid reporting date: Hitliste-YYYYMMDD.csv.":
    "Dateinamen mit gültigem Berichtsdatum verwenden: Hitliste-YYYYMMDD.csv.",
  "Use the individual account created by your administrator.":
    "Das vom Administrator erstellte persönliche Konto verwenden.",
  User: "Benutzer",
  Username: "Benutzername",
  Users: "Benutzer",
  "Users & profiles": "Benutzer & Profile",
  "Valid inspected rows": "Gültige geprüfte Zeilen",
  "View all attention items": "Alle Punkte mit Handlungsbedarf anzeigen",
  "View all highlights": "Alle Hervorhebungen anzeigen",
  "View all open issues": "Alle offenen Probleme anzeigen",
  "View as": "Ansicht als",
  "View history": "Verlauf anzeigen",
  "Viewing as": "Ansicht als",
  Weekly: "Wöchentlich",
  "Welcome to IOP": "Willkommen bei IOP",
  "What happened. What needs attention. What comes next.":
    "Was passiert ist. Was Aufmerksamkeit braucht. Was als Nächstes kommt.",
  "What?": "Was?",
  "Withdraw Start highlight": "Start-Hervorhebung entfernen",
  "Work reference": "Arbeitsreferenz",
  "Write the short update you would share at handover. Add details when needed.":
    "Eine kurze Meldung für die Übergabe schreiben. Bei Bedarf Details ergänzen.",
  "Your department at a glance": "Deine Abteilung auf einen Blick",
  "Your department, open work and important updates.":
    "Deine Abteilung, offene Arbeiten und wichtige Meldungen.",
  "Your history starts with a CSV": "Dein Verlauf beginnt mit einer CSV",
  "Your week · Not connected": "Deine Woche · Nicht verbunden",
  "Your weekly shifts and departments worked will appear here.":
    "Deine wöchentlichen Schichten und Abteilungen erscheinen hier.",
  "Your workspace": "Dein Arbeitsbereich",
  "alarm minutes": "Alarmminuten",
  "alarm minutes/day": "Alarmminuten/Tag",
  bytes: "Bytes",
  "entries ·": "Einträge ·",
  "entries · Showing": "Einträge · Anzeige",
  of: "von",
  "partial — counts may be incomplete":
    "Teilweise — Zahlen können unvollständig sein",
  reference: "Referenz",
  "rows · page": "Zeilen · Seite",
  "technicians read their daily plan; Team Leaders plan assignments; Task Force reads operational and analytical data.":
    "Techniker lesen ihren Tagesplan; Teamleiter planen Einsätze; Task Force liest Betriebs- und Analysedaten.",
  "user administration, imports, workforce configuration, planning and analysis.":
    "Benutzerverwaltung, Importe, Personalkonfiguration, Planung und Analyse.",
  "· Current selection": "· Aktuelle Auswahl",
  "· Layout preview. Your account, data access and permissions remain unchanged.":
    "· Layoutvorschau. Konto, Datenzugriff und Berechtigungen bleiben unverändert.",
  "· Reporting date:": "· Berichtsdatum:",
  "· Revision": "· Version",
  "· monthly daily average": "· monatlicher Tagesdurchschnitt",
  Edit: "Bearbeiten",
  Close: "Schliessen",
  "Download CSV template": "CSV-Vorlage herunterladen",
  "Import preview": "Importvorschau",
  "Import personal schedules before assigning zones. Missing days stay unknown. Email files do not include partial absences.":
    "Persönliche Dienstpläne vor der Bereichszuteilung importieren. Fehlende Tage bleiben unbekannt. E-Mail-Dateien enthalten keine Teilabsenzen.",
  "File must be at most 80 KB.": "Die Datei darf höchstens 80 KB gross sein.",
  "The file could not be read.": "Die Datei konnte nicht gelesen werden.",
  saved: "gespeichert",
  imported: "importiert",
  deleted: "gelöscht",
  "(not in current history)": "(nicht im aktuellen Verlauf)",
  ". Review the existing import; uploading it again would not add data.":
    ". Vorhandenen Import prüfen; ein erneuter Upload fügt keine Daten hinzu.",
  ". Totals, charts and KPI averages use eligible reporting dates. Original files remain available in administration.":
    ". Summen, Diagramme und Kennzahlen berücksichtigen gültige Berichtstage. Originaldateien bleiben in der Administration verfügbar.",
  "; values available in the data tables below":
    "; Werte stehen in den Datentabellen unten",
  "Apply filters to update the table.":
    "Filter anwenden, um die Tabelle zu aktualisieren.",
  Betriebsmittelkennzeichen: "Betriebsmittelkennzeichen",
  Bytes: "Bytes",
  "Daily averages divide by eligible imported dates, including eligible days with no matching errors. Historical reference includes all":
    "Tagesdurchschnitte werden durch die berücksichtigten importierten Tage geteilt, einschliesslich Tagen ohne passende Fehler. Die historische Referenz umfasst alle",
  Häufigkeit: "Häufigkeit",
  IOP: "IOP",
  Meldetext: "Meldetext",
  "Months to compare": "Zu vergleichende Monate",
  "Updating…": "Wird aktualisiert…",
  "eligible days imported. Monthly totals include all eligible matching rows. Missing dates remain gaps. Lower KPI averages are better.":
    "berücksichtigte Tage importiert. Monatssummen umfassen alle passenden Zeilen. Fehlende Tage bleiben Lücken. Niedrigere Kennzahlendurchschnitte sind besser.",
  "eligible imported dates, including this month. Explicit goals override the historical reference. Equal values are neutral; percentages are undefined against zero.":
    "berücksichtigten importierten Tage, einschliesslich dieses Monats. Explizite Ziele ersetzen die historische Referenz. Gleiche Werte sind neutral; Prozentangaben gegenüber null sind nicht definiert.",
  filter: "filtern",
  "groups; charts show the top 10 unless stated. Duration is accumulated alarm time, not plant downtime.":
    "Gruppen; Diagramme zeigen standardmässig die Top 10. Dauer ist die summierte Alarmzeit, keine Anlagenstillstandszeit.",
  "· Discuss in meeting": "· Im Meeting besprechen",
  "· Highlighted": "· Hervorgehoben",
  "· changes pending": "· Änderungen ausstehend",
  "No changes were imported.": "Keine Änderungen importiert.",
  "Entry removed from active views.": "Eintrag aus aktiven Ansichten entfernt.",
  Safety: "Sicherheit",
  Successes: "Erfolge",
  People: "Personal",
  Performance: "Leistung",
  Problems: "Probleme",
  Month: "Monat",
  "Dauer (minutes)": "Dauer (Minuten)",
  "Cumulative share": "Kumulierter Anteil",
  "Alarm duration (minutes)": "Alarmdauer (Minuten)",
  Day: "Tag",
  "Alarm minutes": "Alarmminuten",
  Total: "Gesamt",
  "Cumulative %": "Kumuliert %",
  "Duration (minutes)": "Dauer (Minuten)",
  Bereich: "Bereich",
  Typ: "Typ",
  Meldegruppe: "Meldegruppe",
  "Close {0}": "{0} schliessen",
  "Profile for {0}": "Profil für {0}",
  "Meldetext {0}": "Meldetext {0}",
  "Area {0}": "Bereich {0}",
  "Sector {0}": "Halle {0}",
  "Correction field {0}": "Korrekturfeld {0}",
  "{0} value {1}": "{0}-Wert {1}",
  "· {0} active": "· {0} aktiv",
  "{0} matching rows available.{1}": "{0} passende Zeilen verfügbar.{1}",
  "Welcome, {0}": "Willkommen, {0}",
  "Profile: {0}": "Profil: {0}",
  "Latest imported month · {0}": "Zuletzt importierter Monat · {0}",
  "Areas classified under {0}.": "Bereiche unter {0}.",
  "Add {0} entry": "Eintrag für {0} hinzufügen",
  "/ {0} · Unverified reference": "/ {0} · Ungeprüfte Referenz",
  "Revision {0} · {1} · {2} · {3}": "Version {0} · {1} · {2} · {3}",
  "· Showing {0} of {1}": "· Anzeige {0} von {1}",
  "Earlier and current open issues · {0}":
    "Frühere und aktuelle offene Probleme · {0}",
  "{0} section": "Abschnitt {0}",
  "Main navigation": "Hauptnavigation",
  Challenge: "Herausforderung",
  Cause: "Ursache",
  "The username or password is incorrect.":
    "Benutzername oder Passwort ist falsch.",
  "Sign in to continue.": "Melde dich an, um fortzufahren.",
  "Change your initial password before continuing.":
    "Ändere dein Startpasswort, bevor du fortfährst.",
  "Use a different password of 15 to 128 characters.":
    "Verwende ein anderes Passwort mit 15 bis 128 Zeichen.",
  "Too many attempts. Wait before trying again.":
    "Zu viele Versuche. Warte vor einem erneuten Versuch.",
  "Keep at least one active administrator.":
    "Mindestens ein aktiver Administrator muss erhalten bleiben.",
  "This username is already in use.":
    "Dieser Benutzername wird bereits verwendet.",
  "You do not have permission for this operation.":
    "Du hast keine Berechtigung für diesen Vorgang.",
  "Check the name, username and profile.":
    "Prüfe Name, Benutzername und Profil.",
  "The local user limit has been reached.":
    "Die Grenze für lokale Benutzer wurde erreicht.",
  "The operation could not be completed. Try again.":
    "Der Vorgang konnte nicht abgeschlossen werden. Versuche es erneut.",
  "New entries must use today’s date at your site. Historical dates require a coordinator.":
    "Neue Einträge müssen das heutige Datum am Standort verwenden. Für frühere Daten ist ein Koordinator erforderlich.",
  "Choose a Betriebsmittelkennzeichen from the imported equipment list for this department and area.":
    "Wähle ein Betriebsmittelkennzeichen aus der importierten Anlagenliste für diese Abteilung und diesen Bereich.",
  "You do not have permission for this handover operation.":
    "Du hast keine Berechtigung für diesen Übergabevorgang.",
  "This entry is unavailable.": "Dieser Eintrag ist nicht verfügbar.",
  "This entry or request has changed. Reload the entry before updating it; retry an unchanged publication to recover its saved result.":
    "Dieser Eintrag oder diese Anfrage wurde geändert. Lade den Eintrag vor der Bearbeitung neu. Wiederhole eine unveränderte Veröffentlichung, um das gespeicherte Ergebnis abzurufen.",
  "Check the entry fields, dates and location references.":
    "Prüfe die Eingabefelder, Daten und Standortreferenzen.",
  "Sign in again to use Shift Handover.":
    "Melde dich erneut an, um die Schichtübergabe zu verwenden.",
  "Shift Handover is unavailable. Retry to recover the saved result if publication was interrupted.":
    "Die Schichtübergabe ist nicht verfügbar. Versuche es erneut, um bei unterbrochener Veröffentlichung das gespeicherte Ergebnis abzurufen.",
  "The analytical history needs preparation. Restart the local application with an administrator configured.":
    "Der Analyseverlauf muss aufbereitet werden. Starte die lokale Anwendung mit einem eingerichteten Administrator neu.",
  "The imported data changed. Refresh the data before continuing.":
    "Die importierten Daten wurden geändert. Aktualisiere die Daten, bevor du fortfährst.",
  "Select a local user to continue.":
    "Wähle einen lokalen Benutzer, um fortzufahren.",
  "This user or browser is not permitted to perform this operation.":
    "Dieser Benutzer oder Browser darf diesen Vorgang nicht ausführen.",
  "The CSV exceeds the 5 MiB upload limit.":
    "Die CSV-Datei überschreitet die Uploadgrenze von 5 MiB.",
  "The service is unavailable or busy. Check the API and try again.":
    "Der Dienst ist nicht verfügbar oder ausgelastet. Prüfe die API und versuche es erneut.",
  "Use the supported filename Hitliste-YYYYMMDD.csv.":
    "Verwende den unterstützten Dateinamen Hitliste-YYYYMMDD.csv.",
  "The local storage limit has been reached.":
    "Die lokale Speichergrenze wurde erreicht.",
  "The operation could not be completed. Check the input and try again.":
    "Der Vorgang konnte nicht abgeschlossen werden. Prüfe die Eingaben und versuche es erneut.",
  "The passwords do not match.": "Die Passwörter stimmen nicht überein.",
  "Weekly schedules": "Wochendienstplan",
  "Enter weekly shifts": "Wochenschichten erfassen",
  "Edit week": "Woche bearbeiten",
  "Choose a person, apply a shift to selected days, then adjust individual days.":
    "Wähle eine Person, übertrage eine Schicht auf ausgewählte Tage und passe einzelne Tage an.",
  "Custom work hours": "Individuelle Arbeitszeiten",
  "Saved {0} schedule days.": "{0} Dienstplantage gespeichert.",
  "Apply shift or status": "Schicht oder Status übernehmen",
  "Choose a shift or status": "Schicht oder Status auswählen",
  "Apply to selected days": "Auf ausgewählte Tage anwenden",
  "Select weekdays": "Montag bis Freitag auswählen",
  "Select all days": "Alle Tage auswählen",
  "Clear selection": "Auswahl aufheben",
  "Shift presets apply only on their configured active days. Unplanned days stay empty.":
    "Schichtvorlagen gelten nur an ihren konfigurierten Wochentagen. Ungeplante Tage bleiben leer.",
  "Shift or status": "Schicht oder Status",
  "Not planned": "Nicht geplant",
  "Existing assignment": "Bestehender Einsatz",
  "Existing zone and phone assignments are kept. A conflicting schedule change is rejected without saving any day.":
    "Bestehende Bereichs- und Handyzuweisungen bleiben erhalten. Bei einem Konflikt wird kein Tag gespeichert.",
  "Save week": "Woche speichern",
  "Discard edits": "Änderungen verwerfen",
  "Edit your name": "Eigenen Namen bearbeiten",
  "Edit name": "Namen bearbeiten",
  "Edit name for {0}": "Namen für {0} bearbeiten",
  Time: "Uhrzeit",
};
