-- Up Migration
-- Infrastructure only. Future owning modules grant access only after scope/RLS review.
ALTER DEFAULT PRIVILEGES FOR ROLE iop_migrator REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE iop_migrator REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE iop_migrator REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE iop_migrator REVOKE USAGE ON TYPES FROM PUBLIC;
