/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API process liveness
         * @description Owned by the API host. Public; no identity, permission or organization/site scope required. No inputs: nonempty query strings and request bodies are rejected. JSON/form parsing is capped at 102400 bytes; compressed bodies are unsupported. Does not check database readiness or business access.
         */
        get: operations["getProcessHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_board"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/schedules/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_saveWeek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkforceController_history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_context[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_context[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_switchUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_history"];
        put?: never;
        post: operations["PlatformController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_review"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_recover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_original"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_profile"];
        put?: never;
        post: operations["PlatformController_saveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_messages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/source-rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_sourceRows"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccessController_users"];
        put?: never;
        post: operations["AccessController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccessController_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_rename"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccessController_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HandoverController_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_equipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handover/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HandoverController_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidationIssue: {
            /** @description JSON Pointer into the documented request representation; empty means the whole request. */
            pointer: string;
            /** @enum {string} */
            code: "required" | "invalid" | "out-of-range" | "unsupported";
        };
        ProblemDetails: {
            /** @description Safe business error code. */
            code?: string;
            /** @description Attempt identity for explicit outcome recovery. */
            importId?: string;
            /**
             * Format: uri
             * @example urn:iop:problem:bad-request
             */
            type: string;
            title: string;
            status: number;
            /**
             * Format: uuid
             * @description Server-generated error occurrence identifier; not a client-supplied ID.
             */
            traceId: string;
            /** @description Only present for explicit safe input validation failures (400). */
            errors?: components["schemas"]["ValidationIssue"][];
        };
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        WorkforceRangeDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        WorkforcePersonDto: {
            id: string;
            name: string;
            profile: string;
        };
        WorkforceRecordDto: {
            id: string;
            /** @enum {string} */
            kind: "settings" | "worker" | "schedule" | "assignment";
            revision: number;
            deleted: boolean;
            personName: string;
            /** @description Kind-specific Workforce payload; see docs/development/workforce.md. */
            data: Record<string, never>;
        };
        WorkforceBoardDto: {
            actorId: string;
            timeZone: string;
            canPlan: boolean;
            canAdminister: boolean;
            people: components["schemas"]["WorkforcePersonDto"][];
            settings: Record<string, never>;
            records: components["schemas"]["WorkforceRecordDto"][];
        };
        WorkforceSaveDto: {
            id: string;
            /** @enum {string} */
            kind: "settings" | "worker" | "schedule" | "assignment";
            expectedRevision: number;
            deleted: boolean;
            data: Record<string, never>;
        };
        WorkforceWeekDayDto: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            status: "work" | "compensation" | "training" | "maintenance" | "vacation" | "accident" | "sick" | "off";
            start: string;
            end: string;
            expectedRevision: number;
        };
        WorkforceWeekDto: {
            userId: string;
            /**
             * Format: date
             * @description Monday starting the edited week.
             */
            weekStart: string;
            days: components["schemas"]["WorkforceWeekDayDto"][];
        };
        WorkforceResultDto: {
            changed: number;
            unchanged: number;
        };
        WorkforceImportDto: {
            /** @enum {string} */
            format: "csv" | "email";
            text: string;
            /** @description Explicit target user for an email; CSV has userId per row. */
            userId: string;
        };
        WorkforcePreviewDto: {
            id: string;
            expectedRevision: number;
            data: Record<string, never>;
            /** @enum {string} */
            outcome: "create" | "replace" | "unchanged";
        };
        WorkforceImportRevisionDto: {
            id: string;
            expectedRevision: number;
        };
        WorkforceCommitDto: {
            input: components["schemas"]["WorkforceImportDto"];
            revisions: components["schemas"]["WorkforceImportRevisionDto"][];
        };
        WorkforceHistoryRequestDto: {
            /** @enum {string} */
            kind: "settings" | "worker" | "schedule" | "assignment";
            id: string;
        };
        WorkforceRevisionDto: {
            record: components["schemas"]["WorkforceRecordDto"];
            actorId: string;
            actorName: string;
            at: string;
            action: string;
        };
        LocalUserDto: {
            profile?: string;
            id: string;
            name: string;
        };
        DemoScopeDto: {
            organizationId: string;
            siteId: string;
            sourceId: string;
            siteTimeZone: string;
        };
        DemoContextDto: {
            /** @enum {string} */
            authentication?: "password";
            mustChangePassword?: boolean;
            canAdminister?: boolean;
            canReadAnalytics?: boolean;
            canImport: boolean;
            enabled: boolean;
            users: components["schemas"]["LocalUserDto"][];
            user: components["schemas"]["LocalUserDto"] | null;
            scope: components["schemas"]["DemoScopeDto"] | null;
        };
        SwitchUserDto: {
            userId: string;
        };
        ImportSummaryDto: {
            importId: string;
            originalFilename: string;
            reportingDate: string;
            /** @enum {string} */
            outcome: "received" | "succeeded" | "rejected" | "failed";
            receivedAt: string;
            submittedBy: string;
            admittedRecordCount: number | null;
            reasonCode: string | null;
            byteLength: number;
        };
        DiagnosticDto: {
            code: string;
            line?: number;
            field?: string;
            reason?: string;
        };
        ImportReviewDto: {
            importId: string;
            rawId: string;
            sourceId: string;
            reportingDate: string;
            originalFilename: string;
            sha256: string;
            byteLength: number;
            /** @enum {string} */
            outcome: "received" | "succeeded" | "rejected" | "failed";
            dataRecordCount: number | null;
            admittedRecordCount: number | null;
            rejectedRecordCount: number | null;
            reasonCode: string | null;
            inspectedValidCount: number;
            inspectedInvalidCount: number;
            inspectionComplete: boolean;
            unclassifiedCount: number;
            repeatedCount: number;
            diagnostics: components["schemas"]["DiagnosticDto"][];
            diagnosticsTruncated: boolean;
        };
        AvailabilityDto: {
            revision: string;
            dates: string[];
            latestDate: string | null;
            siteTimeZone: string;
        };
        OptionRequestDto: {
            /** @enum {string} */
            kind: "sector" | "area" | "equipment" | "message";
            revision: string;
            cursor?: string;
            /** @default 50 */
            pageSize: number;
        };
        OptionDto: {
            reference: string;
            label: string;
        };
        OptionsDto: {
            revision: string;
            options: components["schemas"]["OptionDto"][];
            nextCursor: string | null;
        };
        ExecutiveKpiDefinitionDto: {
            id: string;
            label: string;
            message: string;
            /** @enum {string} */
            metric: "frequency" | "duration";
            goal: number | null;
        };
        NormalizationDto: {
            trim: boolean;
            unicodeNfc: boolean;
            collapseWhitespace: boolean;
        };
        AreaSectorDto: {
            area: string;
            sector: string;
        };
        ValueAliasDto: {
            /** @enum {string} */
            field: "area" | "equipment" | "message" | "type" | "messageGroup";
            from: string;
            to: string;
        };
        ReportingProfileDto: {
            executiveKpis?: components["schemas"]["ExecutiveKpiDefinitionDto"][];
            normalization: components["schemas"]["NormalizationDto"];
            unclassifiedLabel: string;
            areaSectors: components["schemas"]["AreaSectorDto"][];
            aliases: components["schemas"]["ValueAliasDto"][];
        };
        ProfileResultDto: {
            version: string;
            profile: components["schemas"]["ReportingProfileDto"];
        };
        MessageCatalogRequestDto: {
            after?: string;
        };
        MessageCatalogDto: {
            values: string[];
            nextCursor: string | null;
        };
        SourceSortDto: {
            /** @enum {string} */
            field: "sector" | "area" | "equipment" | "message" | "type" | "messageGroup";
            /** @enum {string} */
            direction: "asc" | "desc";
        };
        SourceRowsRequestDto: {
            /** @description Exact per-column values combined with AND; minutes match displayed two-decimal values. */
            filters?: {
                [key: string]: string;
            };
            importId: string;
            page: number;
            sort: components["schemas"]["SourceSortDto"][];
            revision?: string;
        };
        ReportRecordDto: {
            area: string;
            equipment: string;
            message: string;
            type: string;
            messageGroup: string;
            sector: string;
            date: string;
            importId: string;
            line: number;
            frequency: number;
            seconds: number;
            minutes: number;
        };
        SourceRowsDto: {
            totalRecordCount?: number;
            options?: {
                [key: string]: string[];
            };
            revision: string;
            records: components["schemas"]["ReportRecordDto"][];
            recordCount: number;
            page: number;
            pageCount: number;
        };
        ReportRequestDto: {
            /** @description Complete calendar months (YYYY-MM) included within the reporting range. */
            months?: string[];
            executive?: boolean;
            from: string;
            toExclusive: string;
            /** @enum {string} */
            dimension: "sector" | "area" | "equipment" | "message" | "type" | "messageGroup" | "frequency" | "duration";
            /** @enum {string} */
            period: "day" | "week" | "month";
            /** @enum {string} */
            metric: "frequency" | "duration";
            filters?: {
                [key: string]: string[];
            };
            search?: string;
            page?: number;
            revision?: string;
        };
        ExecutiveKpiDto: {
            id: string;
            label: string;
            message: string;
            /** @enum {string} */
            metric: "frequency" | "duration";
            goal: number | null;
            total: number;
            average: number | null;
            historicalAverage: number | null;
            reference: number | null;
            /** @enum {string} */
            referenceKind: "goal" | "historical";
            changePercent: number | null;
            /** @enum {string} */
            status: "better" | "worse" | "equal" | "unavailable";
        };
        MonthlyExecutiveDto: {
            month: string;
            importedDays: number;
            calendarDays: number;
            analysisDays?: number;
            historicalDays: number;
            kpis: components["schemas"]["ExecutiveKpiDto"][];
        };
        ReportRowDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
        };
        ExecutiveLeaderDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
            /** @enum {string} */
            dimension: "sector" | "area" | "equipment" | "message";
            /** @enum {string} */
            metric: "frequency" | "duration";
        };
        ReportPointDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
            period: string;
        };
        ReportDto: {
            /** @description Excluded ISO weekdays (Monday 1 through Sunday 7). */
            excludedWeekdays?: number[];
            monthlyExecutive?: components["schemas"]["MonthlyExecutiveDto"];
            revision: string;
            profileVersion: string;
            selection: components["schemas"]["ReportRequestDto"];
            totals: components["schemas"]["ReportRowDto"];
            executive: components["schemas"]["ExecutiveLeaderDto"][];
            groups: components["schemas"]["ReportRowDto"][];
            frequencyGroups: components["schemas"]["ReportRowDto"][];
            durationGroups: components["schemas"]["ReportRowDto"][];
            groupCount: number;
            timeline: components["schemas"]["ReportPointDto"][];
            series: components["schemas"]["ReportPointDto"][];
            monthly: components["schemas"]["ReportPointDto"][];
            options: {
                [key: string]: string[];
            };
            optionCounts: {
                [key: string]: number;
            };
            dates: string[];
            records: components["schemas"]["ReportRecordDto"][];
            recordCount: number;
            page: number;
            pageCount: number;
            unclassifiedCount: number;
        };
        AnalyticalRequestDto: {
            /** @description Inclusive Gregorian reporting-date label. */
            from: string;
            /** @description Exclusive reporting-date label. Maximum range: 366 days. */
            toExclusive: string;
            sectors?: string[];
            areas?: string[];
            equipment?: string[];
            messages?: string[];
            excludedMessages?: string[];
            revision: string;
            /** @default 50 */
            pageSize: number;
            cursor?: string;
        };
        SelectionDto: {
            /** @description Inclusive Gregorian reporting-date label. */
            from: string;
            /** @description Exclusive reporting-date label. Maximum range: 366 days. */
            toExclusive: string;
            sectors?: string[];
            areas?: string[];
            equipment?: string[];
            messages?: string[];
            excludedMessages?: string[];
        };
        FactDto: {
            importId: string;
            rawId: string;
            reportingDate: string;
            sourceRecordNumber: number;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            originalDuration: string;
            sourceArea: string;
            sourceEquipmentReference: string;
            sourceMessageText: string;
            sourceMessageType: string;
            sourceMessageGroup: string;
            repeatedTuple: boolean;
            /** @enum {string} */
            classificationStatus: "mapped" | "unclassified";
            sectorKey: string | null;
            sectorLabel: string;
            sectorRef: string;
            areaRef: string;
            equipmentRef: string;
            messageRef: string;
            mappingRevision: string;
            adapterRevision: string;
            profileRevision: string;
            siteTimeZone: string;
        };
        GroupDto: {
            reference: string;
            label: string;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            recordCount: number;
        };
        GroupsDto: {
            sector: components["schemas"]["GroupDto"][];
            area: components["schemas"]["GroupDto"][];
            equipment: components["schemas"]["GroupDto"][];
            message: components["schemas"]["GroupDto"][];
        };
        GroupCountsDto: {
            sector: number;
            area: number;
            equipment: number;
            message: number;
        };
        AnalysisDto: {
            revision: string;
            selection: components["schemas"]["SelectionDto"];
            recordCount: number;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            admittedDates: string[];
            missingDates: string[];
            /** @enum {string} */
            state: "no-imports" | "no-matches" | "ready";
            unclassifiedCount: number;
            repeatedCount: number;
            records: components["schemas"]["FactDto"][];
            nextCursor: string | null;
            groups: components["schemas"]["GroupsDto"];
            groupCounts: components["schemas"]["GroupCountsDto"];
            /** @enum {string} */
            reportingWindowStatus: "unknown";
        };
        LoginDto: {
            username: string;
            password: string;
        };
        SuccessDto: {
            ok: boolean;
        };
        PasswordDto: {
            currentPassword: string;
            password: string;
        };
        UserProfileDto: {
            name: string;
            username: string;
            /** @enum {string} */
            profile: "administrator" | "technician" | "task-force" | "team-leader";
            id: string;
            active: boolean;
        };
        NewUserDto: {
            name: string;
            username: string;
            /** @enum {string} */
            profile: "administrator" | "technician" | "task-force" | "team-leader";
        };
        CreatedUserDto: {
            user: components["schemas"]["UserProfileDto"];
            initialPassword: string;
        };
        AccessActivityDto: {
            id: string;
            actorName: string;
            subjectName: string;
            action: string;
            recordedAt: string;
        };
        UpdateUserDto: {
            id: string;
            /** @enum {string} */
            profile: "administrator" | "technician" | "task-force" | "team-leader";
            active: boolean;
            name: string;
        };
        ChangeUserDto: {
            id: string;
            /** @enum {string} */
            profile: "administrator" | "technician" | "task-force" | "team-leader";
            active: boolean;
        };
        RenameUserDto: {
            id: string;
            name: string;
        };
        RemoveUserDto: {
            id: string;
        };
        HandoverLocationDto: {
            id: string;
            label: string;
            parentId: string;
            sectorKey: string;
            /** @enum {string} */
            role: "department" | "area" | "location";
        };
        HandoverChoiceDto: {
            carryForward?: boolean;
            id: string;
            label: string;
        };
        HandoverPersonDto: {
            id: string;
            name: string;
        };
        HandoverContextDto: {
            canDelete: boolean;
            locations: components["schemas"]["HandoverLocationDto"][];
            categories: components["schemas"]["HandoverChoiceDto"][];
            people: components["schemas"]["HandoverPersonDto"][];
            canCoordinate: boolean;
            actorId: string;
            externalSystemLabel: string;
            timeZone: string;
        };
        HandoverEquipmentRequestDto: {
            departmentId: string;
            areaId: string;
            search: string;
            after: string;
        };
        HandoverEquipmentPageDto: {
            codes: string[];
            nextCursor: string;
        };
        HandoverSelectionDto: {
            dueFrom?: string;
            dueTo?: string;
            /** @description Omit for all assignees; empty string selects unassigned entries. */
            responsibleId?: string;
            externalReference?: string;
            /** @enum {string} */
            condition?: "" | "damaged" | "inspection-needed" | "blocked" | "repaired" | "restored";
            mine?: boolean;
            attention?: boolean;
            from: string;
            to: string;
            departmentId: string;
            areaId: string;
            equipmentReferenceId: string;
            categoryId: string;
            search: string;
            cursor: string;
            /** @enum {string} */
            state: "" | "none" | "open" | "in-progress" | "resolved" | "pending";
            highlights: boolean;
        };
        HandoverLatestUpdateDto: {
            note: string;
            actorName: string;
            at: string;
        };
        HandoverContentDto: {
            date: string;
            categoryId: string;
            summary: string;
            details: string;
            departmentId: string;
            areaId: string;
            equipmentCode: string;
            equipmentNamespace: string;
            /** @enum {string} */
            condition: "" | "damaged" | "inspection-needed" | "blocked" | "repaired" | "restored";
            externalReference: string;
            challenge: string;
            cause: string;
            measure: string;
            dueDate: string;
            feedbackDueDate: string;
            discuss: boolean;
        };
        HandoverEntryDto: {
            deleted?: boolean;
            latestUpdate?: components["schemas"]["HandoverLatestUpdateDto"];
            id: string;
            authorId: string;
            authorName: string;
            createdAt: string;
            updatedAt: string;
            departmentLabel: string;
            areaLabel: string;
            categoryLabel: string;
            equipmentReferenceId: string;
            responsibleId: string;
            responsibleName: string;
            highlightedAt: string;
            revision: number;
            content: components["schemas"]["HandoverContentDto"];
            /** @enum {string} */
            issueState: "none" | "open" | "in-progress" | "resolved";
            highlighted: boolean;
        };
        HandoverPageDto: {
            entries: components["schemas"]["HandoverEntryDto"][];
            nextCursor: string;
            total: number;
        };
        HandoverCreateDto: {
            key: string;
            responsibleId: string;
            content: components["schemas"]["HandoverContentDto"];
            issue: boolean;
        };
        HandoverChangeDto: {
            id: string;
            note: string;
            expectedRevision: number;
            /** @enum {string} */
            action: "correct" | "follow-up" | "state" | "assign" | "highlight";
            content?: components["schemas"]["HandoverContentDto"];
            /** @enum {string} */
            state?: "none" | "open" | "in-progress" | "resolved";
            responsibleId?: string;
            highlighted?: boolean;
        };
        HandoverHistoryRequestDto: {
            id: string;
            before: number;
        };
        HandoverRevisionDto: {
            entry: components["schemas"]["HandoverEntryDto"];
            actorId: string;
            actorName: string;
            action: string;
            note: string;
            at: string;
        };
        HandoverHistoryDto: {
            entry: components["schemas"]["HandoverEntryDto"];
            revisions: components["schemas"]["HandoverRevisionDto"][];
            nextBefore: number;
        };
        HandoverRemoveDto: {
            id: string;
            expectedRevision: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProcessHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Malformed input, query parameters or body supplied to this no-input operation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description JSON/form parser byte or parameter limit exceeded. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported body encoding or charset. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected host failure; no internal details are exposed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    WorkforceController_board: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceRangeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceBoardDto"];
                };
            };
        };
    };
    WorkforceController_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceSaveDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRecordDto"];
                };
            };
        };
    };
    WorkforceController_saveWeek: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceWeekDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceResultDto"];
                };
            };
        };
    };
    WorkforceController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceImportDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforcePreviewDto"][];
                };
            };
        };
    };
    WorkforceController_commit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceCommitDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceResultDto"];
                };
            };
        };
    };
    WorkforceController_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkforceHistoryRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRevisionDto"][];
                };
            };
        };
    };
    "PlatformController_context[0]": {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContextDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "PlatformController_context[1]": {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContextDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_switchUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContextDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_history: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummaryDto"][];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_submit: {
        parameters: {
            query?: never;
            header: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
                /** @description Supported Hitliste-YYYYMMDD.csv reporting label. */
                "X-CSV-Filename": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_review: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_recover: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_original: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original CSV bytes; requires imports.review. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_availability: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_options: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_profile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResultDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_saveProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileResultDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResultDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_messages: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCatalogRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCatalogDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_sourceRows: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRowsRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRowsDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_report: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_query: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticalRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccessController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"][];
                };
            };
        };
    };
    AccessController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUserDto"];
                };
            };
        };
    };
    AccessController_activity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessActivityDto"][];
                };
            };
        };
    };
    AccessController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    AccessController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessDto"];
                };
            };
        };
    };
    HandoverController_context: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverContextDto"];
                };
            };
        };
    };
    HandoverController_equipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverEquipmentRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverEquipmentPageDto"];
                };
            };
        };
    };
    HandoverController_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverSelectionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverPageDto"];
                };
            };
        };
    };
    HandoverController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverEntryDto"];
                };
            };
        };
    };
    HandoverController_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverChangeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverEntryDto"];
                };
            };
        };
    };
    HandoverController_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverHistoryRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverHistoryDto"];
                };
            };
        };
    };
    HandoverController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoverRemoveDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoverEntryDto"];
                };
            };
        };
    };
}
