/** IOP identity v1. Preserve these tokens unless the owner explicitly requests a visual change. */
export const identity = {
  ink: "#172b43",
  muted: "#64758b",
  line: "#dce5ed",
  primary: "#087bd5",
  canvas: "#f3f6f9",
  surface: "#ffffff",
  inputBorder: "#cbd7e2",
  focus: "#edaa30",
  link: "#076bb5",
  disclosureInk: "#174e69",
  activeSurface: "#e8f3fc",
  activeInk: "#096faf",
  successInk: "#18734a",
  successSurface: "#eef8f2",
  successBorder: "#b9dec8",
  warningInk: "#805500",
  warningSurface: "#fff5d6",
  errorSurface: "#fff1f0",
  errorBorder: "#efb8b3",
  errorInk: "#9c2424",
  chartFrequency: "#138df4",
  chartComparison: "#2424a5",
  chartAccent: "#f3773d",
  chartTeal: "#147e8a",
  chartPurple: "#a755ad",
  chartDuration: "#164f84",
  chartText: "#576779",
  heatmapLow: "#e8f4ff",
  heatmapHigh: "#0875cc",
  font: "Inter, system-ui, sans-serif",
  bodySize: "14px",
  pageTitleSize: "28px",
  sectionTitleSize: "16px",
  captionSize: "12.8px",
  smallSize: "11px",
  compactSize: "12px",
  eyebrowSize: "10px",
  chartTitleSize: "15px",
  brandSize: "25px",
  brandCompactSize: "19px",
  metricCompactSize: "24px",
  iconSize: "22.4px",
  regularWeight: "400",
  mediumWeight: "500",
  labelWeight: "600",
  headingWeight: "700",
  chartTitleWeight: "550",
  brandWeight: "800",
  titleLineHeight: "1.2",
  bodyLineHeight: "1.6",
  captionLineHeight: "1.5",
  metricLineHeight: "1.3",
  panelPadding: "20px",
  sectionGap: "16px",
  cardRadius: "8px",
  metricRadius: "7px",
  controlRadius: "5px",
  toolbarControlSize: "44px",
  toolbarIconSize: "20px",
  toolbarGap: "10px",
  inputRadius: "4px",
  metricSize: "29px",
  metricWeight: "650",
  metricPadding: "19px",
  metricGap: "14px",
} as const;

export const identityVariables = Object.fromEntries(
  Object.entries(identity).map(([name, value]) => [`--iop-${name}`, value]),
);
export const chartPalette = [
  identity.chartFrequency,
  identity.chartComparison,
  identity.chartAccent,
  identity.chartTeal,
  identity.chartPurple,
];
