/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API process liveness
         * @description Owned by the API host. Public; no identity, permission or organization/site scope required. No inputs. Does not check database readiness or business access.
         */
        get: operations["getProcessHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidationIssue: {
            /** @description JSON Pointer into the documented request representation; empty means the whole request. */
            pointer: string;
            /** @enum {string} */
            code: "required" | "invalid" | "out-of-range" | "unsupported";
        };
        ProblemDetails: {
            /**
             * Format: uri
             * @example urn:iop:problem:bad-request
             */
            type: string;
            title: string;
            status: number;
            /**
             * Format: uuid
             * @description Server-generated error occurrence identifier; not a client-supplied ID.
             */
            traceId: string;
            /** @description Only present for explicit safe input validation failures (400). */
            errors?: components["schemas"]["ValidationIssue"][];
        };
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProcessHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Unexpected host failure; no internal details are exposed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
