/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API process liveness
         * @description Owned by the API host. Public; no identity, permission or organization/site scope required. No inputs: nonempty query strings and request bodies are rejected. JSON/form parsing is capped at 102400 bytes; compressed bodies are unsupported. Does not check database readiness or business access.
         */
        get: operations["getProcessHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_switchUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_history"];
        put?: never;
        post: operations["PlatformController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_review"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_recover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_original"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PlatformController_profile"];
        put?: never;
        post: operations["PlatformController_saveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlatformController_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidationIssue: {
            /** @description JSON Pointer into the documented request representation; empty means the whole request. */
            pointer: string;
            /** @enum {string} */
            code: "required" | "invalid" | "out-of-range" | "unsupported";
        };
        ProblemDetails: {
            /** @description Safe business error code. */
            code?: string;
            /** @description Attempt identity for explicit outcome recovery. */
            importId?: string;
            /**
             * Format: uri
             * @example urn:iop:problem:bad-request
             */
            type: string;
            title: string;
            status: number;
            /**
             * Format: uuid
             * @description Server-generated error occurrence identifier; not a client-supplied ID.
             */
            traceId: string;
            /** @description Only present for explicit safe input validation failures (400). */
            errors?: components["schemas"]["ValidationIssue"][];
        };
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        LocalUserDto: {
            id: string;
            name: string;
        };
        DemoScopeDto: {
            organizationId: string;
            siteId: string;
            sourceId: string;
            siteTimeZone: string;
        };
        DemoContextDto: {
            canImport: boolean;
            enabled: boolean;
            users: components["schemas"]["LocalUserDto"][];
            user: components["schemas"]["LocalUserDto"] | null;
            scope: components["schemas"]["DemoScopeDto"] | null;
        };
        SwitchUserDto: {
            userId: string;
        };
        ImportSummaryDto: {
            importId: string;
            originalFilename: string;
            reportingDate: string;
            /** @enum {string} */
            outcome: "received" | "succeeded" | "rejected" | "failed";
            receivedAt: string;
            submittedBy: string;
            admittedRecordCount: number | null;
            reasonCode: string | null;
            byteLength: number;
        };
        DiagnosticDto: {
            code: string;
            line?: number;
            field?: string;
            reason?: string;
        };
        ImportReviewDto: {
            importId: string;
            rawId: string;
            sourceId: string;
            reportingDate: string;
            originalFilename: string;
            sha256: string;
            byteLength: number;
            /** @enum {string} */
            outcome: "received" | "succeeded" | "rejected" | "failed";
            dataRecordCount: number | null;
            admittedRecordCount: number | null;
            rejectedRecordCount: number | null;
            reasonCode: string | null;
            inspectedValidCount: number;
            inspectedInvalidCount: number;
            inspectionComplete: boolean;
            unclassifiedCount: number;
            repeatedCount: number;
            diagnostics: components["schemas"]["DiagnosticDto"][];
            diagnosticsTruncated: boolean;
        };
        AvailabilityDto: {
            revision: string;
            dates: string[];
            latestDate: string | null;
            siteTimeZone: string;
        };
        OptionRequestDto: {
            /** @enum {string} */
            kind: "sector" | "area" | "equipment" | "message";
            revision: string;
            cursor?: string;
            /** @default 50 */
            pageSize: number;
        };
        OptionDto: {
            reference: string;
            label: string;
        };
        OptionsDto: {
            revision: string;
            options: components["schemas"]["OptionDto"][];
            nextCursor: string | null;
        };
        NormalizationDto: {
            trim: boolean;
            unicodeNfc: boolean;
            collapseWhitespace: boolean;
        };
        AreaSectorDto: {
            area: string;
            sector: string;
        };
        ValueAliasDto: {
            /** @enum {string} */
            field: "area" | "equipment" | "message" | "type" | "messageGroup";
            from: string;
            to: string;
        };
        ReportingProfileDto: {
            normalization: components["schemas"]["NormalizationDto"];
            unclassifiedLabel: string;
            areaSectors: components["schemas"]["AreaSectorDto"][];
            aliases: components["schemas"]["ValueAliasDto"][];
        };
        ProfileResultDto: {
            version: string;
            profile: components["schemas"]["ReportingProfileDto"];
        };
        ReportRequestDto: {
            from: string;
            toExclusive: string;
            /** @enum {string} */
            dimension: "sector" | "area" | "equipment" | "message" | "type" | "messageGroup" | "frequency" | "duration";
            /** @enum {string} */
            period: "day" | "week" | "month";
            /** @enum {string} */
            metric: "frequency" | "duration";
            filters?: {
                [key: string]: string[];
            };
            search?: string;
            page?: number;
            revision?: string;
        };
        ReportRowDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
        };
        ExecutiveLeaderDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
            /** @enum {string} */
            dimension: "sector" | "area" | "equipment" | "message";
            /** @enum {string} */
            metric: "frequency" | "duration";
        };
        ReportPointDto: {
            key: string;
            frequency: number;
            seconds: number;
            minutes: number;
            records: number;
            period: string;
        };
        ReportRecordDto: {
            area: string;
            equipment: string;
            message: string;
            type: string;
            messageGroup: string;
            sector: string;
            date: string;
            importId: string;
            line: number;
            frequency: number;
            seconds: number;
            minutes: number;
        };
        ReportDto: {
            revision: string;
            profileVersion: string;
            selection: components["schemas"]["ReportRequestDto"];
            totals: components["schemas"]["ReportRowDto"];
            executive: components["schemas"]["ExecutiveLeaderDto"][];
            groups: components["schemas"]["ReportRowDto"][];
            durationGroups: components["schemas"]["ReportRowDto"][];
            groupCount: number;
            timeline: components["schemas"]["ReportPointDto"][];
            series: components["schemas"]["ReportPointDto"][];
            monthly: components["schemas"]["ReportPointDto"][];
            options: {
                [key: string]: string[];
            };
            optionCounts: {
                [key: string]: number;
            };
            dates: string[];
            records: components["schemas"]["ReportRecordDto"][];
            recordCount: number;
            page: number;
            pageCount: number;
            unclassifiedCount: number;
        };
        AnalyticalRequestDto: {
            /** @description Inclusive Gregorian reporting-date label. */
            from: string;
            /** @description Exclusive reporting-date label. Maximum range: 366 days. */
            toExclusive: string;
            sectors?: string[];
            areas?: string[];
            equipment?: string[];
            messages?: string[];
            excludedMessages?: string[];
            revision: string;
            /** @default 50 */
            pageSize: number;
            cursor?: string;
        };
        SelectionDto: {
            /** @description Inclusive Gregorian reporting-date label. */
            from: string;
            /** @description Exclusive reporting-date label. Maximum range: 366 days. */
            toExclusive: string;
            sectors?: string[];
            areas?: string[];
            equipment?: string[];
            messages?: string[];
            excludedMessages?: string[];
        };
        FactDto: {
            importId: string;
            rawId: string;
            reportingDate: string;
            sourceRecordNumber: number;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            originalDuration: string;
            sourceArea: string;
            sourceEquipmentReference: string;
            sourceMessageText: string;
            sourceMessageType: string;
            sourceMessageGroup: string;
            repeatedTuple: boolean;
            /** @enum {string} */
            classificationStatus: "mapped" | "unclassified";
            sectorKey: string | null;
            sectorLabel: string;
            sectorRef: string;
            areaRef: string;
            equipmentRef: string;
            messageRef: string;
            mappingRevision: string;
            adapterRevision: string;
            profileRevision: string;
            siteTimeZone: string;
        };
        GroupDto: {
            reference: string;
            label: string;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            recordCount: number;
        };
        GroupsDto: {
            sector: components["schemas"]["GroupDto"][];
            area: components["schemas"]["GroupDto"][];
            equipment: components["schemas"]["GroupDto"][];
            message: components["schemas"]["GroupDto"][];
        };
        GroupCountsDto: {
            sector: number;
            area: number;
            equipment: number;
            message: number;
        };
        AnalysisDto: {
            revision: string;
            selection: components["schemas"]["SelectionDto"];
            recordCount: number;
            reportedFrequency: number;
            accumulatedAlarmSeconds: number;
            admittedDates: string[];
            missingDates: string[];
            /** @enum {string} */
            state: "no-imports" | "no-matches" | "ready";
            unclassifiedCount: number;
            repeatedCount: number;
            records: components["schemas"]["FactDto"][];
            nextCursor: string | null;
            groups: components["schemas"]["GroupsDto"];
            groupCounts: components["schemas"]["GroupCountsDto"];
            /** @enum {string} */
            reportingWindowStatus: "unknown";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProcessHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Malformed input, query parameters or body supplied to this no-input operation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description JSON/form parser byte or parameter limit exceeded. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported body encoding or charset. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected host failure; no internal details are exposed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PlatformController_context: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContextDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_switchUser: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoContextDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_history: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummaryDto"][];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_submit: {
        parameters: {
            query?: never;
            header: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
                /** @description Supported Hitliste-YYYYMMDD.csv reporting label. */
                "X-CSV-Filename": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_review: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_recover: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_original: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original CSV bytes; requires imports.review. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_availability: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_options: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_profile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResultDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_saveProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileResultDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResultDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_report: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlatformController_query: {
        parameters: {
            query?: never;
            header?: {
                /** @description Value 1 required on POST, together with an allowed Origin and local session cookie. */
                "X-IOP-Demo"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticalRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDto"];
                };
            };
            /** @description Invalid bounded input or unavailable reference. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Select a configured local demo user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope, current grants, host or browser origin denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Revision changed or import capacity/recovery conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exact analytical total exceeds the supported integer range. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Local mode inactive, maintenance, busy upload or persistence unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
